version: '3.11.4'
services:
  app:
    build: .
    volumes:
      - .:/todo
    ports:
      - "8000:8000"
    image: app:todo
    container_name: my_todo_container
    command: python manage.py runserver 0.0.0.0:8000
