# Use an official Python runtime as the base image
FROM python:3.11-slim

# Set environment variables
ENV PYTHONBUFFERED=1

# Set the working directory in the container
WORKDIR /todo

# Copy the requirements file into the container
COPY requirements.txt requirements.txt

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

# Set the command to run when the container starts
CMD python manage.py runserver 0.0.0.0.8000
